# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83787c9ceb15337f51b12c671f01b270a78f25ab2e71416492a6b4b242acbeb8414bd28ba65d3be908f191b4b6dacd14fcc763d49e180e7d54a2324725b1d9a6

test:
  secret_key_base: 6481d6ed65cdc1f5e6ea1cce61d5f3f89c71a52ce145d3b3e3ff6c258a10dbccd7f01da195b486171a06ce4be886b46ac1c34140a1875413ac868167517fee86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
